export const FETCH_WORD_REQUEST = "FETCH_WORD_REQUEST";
export const FETCH_WORD_RECEIVED = "FETCH_WORD_RECEIVED";
export const FETCH_WORD_ERROR = "FETCH_WORD_RECEIVED";
export const PRESS_KEY = "PRESS_KEY";
export const END_THE_GAME = "END_THE_GAME";
export const RESET_THE_GAME = 'RESET_THE_GAME';
